FROM node:lts-alpine3.17 AS build

ENV TZ="America/Lima"

RUN apk add --no-cache tzdata

WORKDIR /usr/src/app
COPY ./app/package*.json ./

RUN npm install
RUN npm install -g @angular/cli

COPY ./app ./

RUN ng build 

FROM nginx:1.21.0-alpine

ENV TZ="America/Lima"

RUN apk add --no-cache tzdata

COPY ./nginx.conf /etc/nginx/nginx.conf

 COPY --from=build /usr/src/app /usr/share/nginx/html 